package eu.kanade.tachiyomi.extension.all.rezka

internal data class SectionFilterConfig(
    val genres: List<GenreOption>,
    val collections: List<CollectionOption>,
)

internal val BROWSE_MODE_OPTIONS = listOf(
    BrowseModeOption(label = "Каталог", mode = BrowseMode.CATALOG),
    BrowseModeOption(label = "Топ по году", mode = BrowseMode.BEST_BY_YEAR),
    BrowseModeOption(label = "Коллекции", mode = BrowseMode.COLLECTIONS),
)

internal val LISTING_MODES = listOf(
    ListingModeOption(label = "Последние поступления", queryValue = null),
    ListingModeOption(label = "Популярные", queryValue = "popular"),
    ListingModeOption(label = "В ожидании", queryValue = "soon"),
    ListingModeOption(label = "Сейчас смотрят", queryValue = "watching"),
)

internal val ALL_GENRES = GenreOption(label = "Все жанры", slug = null)

internal val SECTION_FILTER_CONFIGS = mapOf(
    "films" to SectionFilterConfig(
        genres = listOf(
            ALL_GENRES,
            GenreOption("Вестерны", "western"),
            GenreOption("Семейные", "family"),
            GenreOption("Фэнтези", "fantasy"),
            GenreOption("Биографические", "biographical"),
            GenreOption("Арт-хаус", "arthouse"),
            GenreOption("Боевики", "action"),
            GenreOption("Военные", "military"),
            GenreOption("Детективы", "detective"),
            GenreOption("Криминал", "crime"),
            GenreOption("Приключения", "adventures"),
            GenreOption("Драмы", "drama"),
            GenreOption("Спортивные", "sport"),
            GenreOption("Фантастика", "fiction"),
            GenreOption("Комедии", "comedy"),
            GenreOption("Мелодрамы", "melodrama"),
            GenreOption("Триллеры", "thriller"),
            GenreOption("Ужасы", "horror"),
            GenreOption("Музыкальные", "musical"),
            GenreOption("Исторические", "historical"),
            GenreOption("Документальные", "documentary"),
            GenreOption("Эротика", "erotic"),
            GenreOption("Детские", "kids"),
            GenreOption("Путешествия", "travel"),
            GenreOption("Познавательные", "cognitive"),
            GenreOption("Театр", "theatre"),
            GenreOption("Концерт", "concert"),
            GenreOption("Стендап", "standup"),
            GenreOption("Короткометражные", "short"),
            GenreOption("Русские", "russian"),
            GenreOption("Украинские", "ukrainian"),
            GenreOption("Зарубежные", "foreign"),
        ),
        collections = listOf(
            CollectionOption("Netflix", "834-filmy-netflix"),
            CollectionOption("HBO и HBO Max", "1419-filmy-hbo"),
            CollectionOption("Amazon", "1417-filmy-amazon"),
            CollectionOption("Disney", "1075-filmy-disney"),
            CollectionOption("Apple TV+", "1416-filmy-apple-tv"),
        ),
    ),
    "series" to SectionFilterConfig(
        genres = listOf(
            ALL_GENRES,
            GenreOption("Военные", "military"),
            GenreOption("Боевики", "action"),
            GenreOption("Арт-хаус", "arthouse"),
            GenreOption("Триллеры", "thriller"),
            GenreOption("Ужасы", "horror"),
            GenreOption("Приключения", "adventures"),
            GenreOption("Семейные", "family"),
            GenreOption("Фантастика", "fiction"),
            GenreOption("Фэнтези", "fantasy"),
            GenreOption("Драмы", "drama"),
            GenreOption("Мелодрамы", "melodrama"),
            GenreOption("Спортивные", "sport"),
            GenreOption("Комедии", "comedy"),
            GenreOption("Детективы", "detective"),
            GenreOption("Криминал", "crime"),
            GenreOption("Исторические", "historical"),
            GenreOption("Биографические", "biographical"),
            GenreOption("Вестерны", "western"),
            GenreOption("Документальные", "documentary"),
            GenreOption("Музыкальные", "musical"),
            GenreOption("Реальное ТВ", "realtv"),
            GenreOption("Телепередачи", "telecasts"),
            GenreOption("Стендап", "standup"),
            GenreOption("Эротика", "erotic"),
            GenreOption("Русские", "russian"),
            GenreOption("Украинские", "ukrainian"),
            GenreOption("Зарубежные", "foreign"),
        ),
        collections = listOf(
            CollectionOption("Netflix", "640-serialy-netflix"),
            CollectionOption("HBO и HBO Max", "639-serialy-hbo"),
            CollectionOption("Amazon Prime", "831-serialy-amazon"),
            CollectionOption("Disney+", "1148-serialy-disney"),
            CollectionOption("Apple TV+", "1146-serialy-apple-tv"),
            CollectionOption("Hulu", "813-serialy-hulu"),
            CollectionOption("Epix", "1251-serialy-epix"),
        ),
    ),
    "cartoons" to SectionFilterConfig(
        genres = listOf(
            ALL_GENRES,
            GenreOption("Фантастика", "fiction"),
            GenreOption("Фэнтези", "fantasy"),
            GenreOption("Боевики", "action"),
            GenreOption("Биографические", "biographical"),
            GenreOption("Комедии", "comedy"),
            GenreOption("Вестерны", "western"),
            GenreOption("Военные", "military"),
            GenreOption("Драмы", "drama"),
            GenreOption("Мелодрамы", "melodrama"),
            GenreOption("Арт-хаус", "arthouse"),
            GenreOption("Детективы", "detective"),
            GenreOption("Криминал", "crime"),
            GenreOption("Триллеры", "thriller"),
            GenreOption("Исторические", "historical"),
            GenreOption("Документальные", "documentary"),
            GenreOption("Эротика", "erotic"),
            GenreOption("Сказки", "fairytale"),
            GenreOption("Семейные", "family"),
            GenreOption("Ужасы", "horror"),
            GenreOption("Приключения", "adventures"),
            GenreOption("Спортивные", "sport"),
            GenreOption("Познавательные", "cognitive"),
            GenreOption("Мюзиклы", "musical"),
            GenreOption("Аниме", "anime"),
            GenreOption("Детские", "kids"),
            GenreOption("Для взрослых", "adult"),
            GenreOption("Мультсериалы", "multseries"),
            GenreOption("Короткометражные", "short"),
            GenreOption("Полнометражные", "full-length"),
            GenreOption("Советские", "soyzmyltfilm"),
            GenreOption("Русские", "russian"),
            GenreOption("Украинские", "ukrainian"),
            GenreOption("Зарубежные", "foreign"),
        ),
        collections = listOf(
            CollectionOption("Netflix", "1004-animacionnye-serialy-netflix"),
            CollectionOption("Disney", "1-multfilmy-disney"),
        ),
    ),
    "anime" to SectionFilterConfig(
        genres = listOf(
            ALL_GENRES,
            GenreOption("Военные", "military"),
            GenreOption("Драмы", "drama"),
            GenreOption("Детективы", "detective"),
            GenreOption("Триллеры", "thriller"),
            GenreOption("Комедии", "comedy"),
            GenreOption("Фантастика", "fiction"),
            GenreOption("Фэнтези", "fantasy"),
            GenreOption("Приключения", "adventures"),
            GenreOption("Романтические", "romance"),
            GenreOption("Исторические", "historical"),
            GenreOption("Ужасы", "horror"),
            GenreOption("Мистические", "mystery"),
            GenreOption("Музыкальные", "musical"),
            GenreOption("Эротика", "erotic"),
            GenreOption("Боевики", "action"),
            GenreOption("Боевые искусства", "fighting"),
            GenreOption("Самурайский боевик", "samurai"),
            GenreOption("Спортивные", "sport"),
            GenreOption("Образовательные", "educational"),
            GenreOption("Повседневность", "everyday"),
            GenreOption("Пародия", "parody"),
            GenreOption("Школа", "school"),
            GenreOption("Детские", "kids"),
            GenreOption("Сказки", "fairytale"),
            GenreOption("Кодомо", "kodomo"),
            GenreOption("Сёдзё-ай", "shoujoai"),
            GenreOption("Сёдзё", "shoujo"),
            GenreOption("Сёнэн", "shounen"),
            GenreOption("Сёнэн-ай", "shounenai"),
            GenreOption("Этти", "ecchi"),
            GenreOption("Махо-сёдзё", "mahoushoujo"),
            GenreOption("Меха", "mecha"),
        ),
        collections = listOf(
            CollectionOption("Netflix", "1242-anime-netflix"),
        ),
    ),
)
